package com.example.coderag.chunker;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

class LowValueDetectorServiceTest {

    private LowValueDetectorService detector;

    @BeforeEach
    void setUp() {
        detector = new LowValueDetectorService();
    }

    @Test
    void detect_ShouldSkipEmptyOrBlankFiles() {
        var emptyRes = detector.detect(Collections.emptyList(), 0);
        assertTrue(emptyRes.isLowValue());
        assertTrue(emptyRes.reason().contains("Empty file"));

        var blankRes = detector.detect(List.of("   ", "\t", ""), 10);
        assertTrue(blankRes.isLowValue());
        assertTrue(blankRes.reason().contains("whitespace"));
    }

    @Test
    void detect_ShouldKeepNormalCodeFile() {
        List<String> lines = List.of(
                "package com.example.service;",
                "",
                "import org.springframework.stereotype.Service;",
                "",
                "@Service",
                "public class GreetingService {",
                "    public String greet(String name) {",
                "        return \"Hello, \" + name + \"!\";",
                "    }",
                "}"
        );

        var result = detector.detect(lines, 200);
        assertFalse(result.isLowValue());
    }

    @Test
    void detect_ShouldSkipMinifiedCode_MaxLineLengthExceeded() {
        String longLine = "var a=1;".repeat(150); // ~1350 characters
        List<String> lines = List.of(longLine);

        var result = detector.detect(lines, longLine.length());
        assertTrue(result.isLowValue());
        assertTrue(result.reason().contains("exceeds 1000 characters"));
    }

    @Test
    void detect_ShouldSkipMinifiedCode_AverageLineLengthExceeded() {
        // 2 lines, each 400 chars -> total 800 chars, avg 400 > 300
        String line1 = "function test(){console.log('x');}".repeat(12);
        String line2 = "function test2(){console.log('y');}".repeat(12);
        List<String> lines = List.of(line1, line2);

        var result = detector.detect(lines, line1.length() + line2.length());
        assertTrue(result.isLowValue());
        assertTrue(result.reason().contains("average line length"));
    }

    @Test
    void detect_ShouldSkipGeneratedCode_InHeader() {
        List<String> lines = List.of(
                "// Code generated by protoc-gen-go. DO NOT EDIT.",
                "// source: user.proto",
                "package pb",
                "",
                "type User struct {",
                "    Id string",
                "}"
        );

        var result = detector.detect(lines, 200);
        assertTrue(result.isLowValue());
        assertTrue(result.reason().contains("Generated code detected"));
    }

    @Test
    void detect_ShouldSkipGeneratedCode_AtGeneratedTag() {
        List<String> lines = List.of(
                "/**",
                " * @generated by GraphQL Codegen",
                " */",
                "export type Query = {",
                "    user: User;",
                "};"
        );

        var result = detector.detect(lines, 200);
        assertTrue(result.isLowValue());
        assertTrue(result.reason().contains("Generated code detected"));
    }
}
