package com.example.coderag.chunker;

import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Locale;

@Service
public class LowValueDetectorService {

    private static final List<String> GENERATED_PATTERNS = List.of(
            "do not edit",
            "auto-generated",
            "autogenerated",
            "generated by",
            "@generated",
            "this file was automatically generated",
            "<auto-generated>"
    );

    public record DetectionResult(boolean isLowValue, String reason) {
        public static DetectionResult keep() {
            return new DetectionResult(false, null);
        }

        public static DetectionResult skip(String reason) {
            return new DetectionResult(true, reason);
        }
    }

    public DetectionResult detect(List<String> lines, long sizeBytes) {
        if (lines == null || lines.isEmpty()) {
            return DetectionResult.skip("Empty file");
        }

        boolean allBlank = true;
        for (String line : lines) {
            if (!line.isBlank()) {
                allBlank = false;
                break;
            }
        }
        if (allBlank) {
            return DetectionResult.skip("File contains only whitespace");
        }

        int lineCount = lines.size();
        long totalChars = 0;
        int maxLineLength = 0;

        for (String line : lines) {
            int len = line.length();
            totalChars += len;
            if (len > maxLineLength) {
                maxLineLength = len;
            }
        }

        // Heuristic: Max line length > 1000 characters
        if (maxLineLength > 1000) {
            return DetectionResult.skip("Likely minified: line exceeds 1000 characters (" + maxLineLength + " chars)");
        }

        // Heuristic: Average line length > 300 characters
        double avgLineLength = (double) totalChars / lineCount;
        if (avgLineLength > 300.0 && totalChars > 500) {
            return DetectionResult.skip(String.format(Locale.ROOT, "Likely minified: average line length %.1f > 300", avgLineLength));
        }

        // Heuristic: Low newline ratio for medium/large files
        if (totalChars > 500) {
            double newlineRatio = (double) lineCount / totalChars;
            if (newlineRatio < 0.005) {
                return DetectionResult.skip(String.format(Locale.ROOT, "Likely minified: newline ratio %.4f < 0.005", newlineRatio));
            }
        }

        // Heuristic: Generated code comments in the first 10 lines
        int headerLinesToCheck = Math.min(10, lines.size());
        for (int i = 0; i < headerLinesToCheck; i++) {
            String lower = lines.get(i).toLowerCase(Locale.ROOT);
            for (String pattern : GENERATED_PATTERNS) {
                if (lower.contains(pattern)) {
                    return DetectionResult.skip("Generated code detected: matches '" + pattern + "' in header");
                }
            }
        }

        return DetectionResult.keep();
    }
}
